name: Release

on:
  release:
      types: [published]

jobs: 
  release:
    name: "Build and publish package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: "Install hatch"
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      
      - name: "Check release version"
        run: bash scripts/check_version.sh "${{ github.ref_name }}"

      - name: "Replace relative markdown links"
        run: python3 scripts/replace_relative_md_links.py --github-repo "${{ github.repository }}" README.md
      
      - name: "Build package"
        run: hatch build

      - name: "Publish to Pypi"
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with: 
          password: ${{ secrets.PYPI_API_TOKEN }}

      