name: Run tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: "Check linter and format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
        
      - name: "Check linter"
        uses: chartboost/ruff-action@v1
      
      - name: "Check format"
        uses: chartboost/ruff-action@v1
        with:
          args: format --check


  tests:
    name: "Run tests with python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: pip install hatch

      - name: Run tests
        run: hatch run test

